# Generated by Django 5.1.4 on 2025-01-02 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='birth_day',
            new_name='birth_date',
        ),
    ]
