# Generated by Django 5.1.4 on 2025-01-10 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_rename_birth_day_customer_birth_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='Customer',
            new_name='customer',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='Customer',
            new_name='customer',
        ),
    ]
